# Site settings
title: Rockpell's Blog
email: aythffk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is Rockpell's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: null
github_username:  rockpell

# Build settings
markdown: kramdown
